load And3.hdl;
output-file And3.out;
compare-to And3.cmp;
output-list a b c out;
set a 0, set b 0, set c 0, eval, output;
set a 0, set b 1, set c 0, eval, output;
set a 1, set b 0, set c 0, eval, output;
set a 1, set b 1, set c 0, eval, output;
set a 0, set b 0, set c 1, eval, output;
set a 0, set b 1, set c 1, eval, output;
set a 1, set b 0, set c 1, eval, output;
set a 1, set b 1, set c 1, eval, output;
